### ISSUE TITLE
Deleting events vs. Labeling events in ReviewEventsGUI

### ISSUE THREAD

**Issue by willpower2727** [pabloi/labTools#11]
Can anyone shed some insight on the differences between the delete events buttons and the label as good/bad buttons in the ReviewEventsGUI? In case you don't know, Pressing the "delete" buttons places a call to re-calculate the parameters:

line 625
expData.data{handles.idx}.adaptParams=calcParameters(expData.data{handles.idx},expData.subData);

When the label as "bad" button is pressed, line 719 the expData instance is simply updated, and then it re-plots in the GUI.

expData.data{handles.idx}.adaptParams.Data(loc,idxs)=[true, false]; 

Is the call to re-calculate parameters necessary? If labeling an event as "bad" has the same end affect as deleting the events, it would be much much much much faster to skip the call to re-calculate parameters. For example, when reviewing stroke or stroke control data, deleting an event on a long trial (6-10 minutes) takes several minutes per call to calcparams(). Typically there are a few events to delete and they don't always happen in the same time frame. So I end up deleting events multiple times per trial. Long story short, it takes all afternoon to review the events of a stroke/control subject.

If anyone can explain why we are calling calcparams I'd be grateful. If no one knows, and "bad" events are still ignored in the end, I'd suggest we avoid using the delete buttons.

**Comment by willpower2727** [comment]
Here's a profile of a simple session in ReviewEventsGUI. I called the delete button 1 time and it took 12 seconds to finish the call to calcparams().

[profileexample.pdf](https://github.com/pabloi/labTools/files/8801/profileexample.pdf)

**Comment by pabloi** [comment]
This is a great question. The short answer is this:
When you mark a stride as bad, you are keeping the events and all the parameters that correspond to that stride, but saying that we believe there is a problem with the data and therefore that data should not be considered.
When you delete an event, you are changing the stride definition (e.g. if you delete a slow heel-strike, you effectively join the stride before with the stride that comes after into a single stride, as there no longer is a separating event between them). Because the strides change, parameters need to be re-computed (at least for the affected strides). This is why the calcParameters() call is forced upon event deletion/addition.

I agree this may lead to very long/painful sessions of reviewing events, but both functionalities (mark as bad and delete) should be preserved as they are. We could however implement some ameliorating changes such as:
1) Upon event addition/deletion: only re-compute events for directly affected strides, and incorporate them into adaptParams in a way that is consistent with the new stride numbering.
2) Check if calcParameters() is being called even when we add/remove a TO event. This could be skipped (we would have to force a call to calcParameters() upon saving or writing to disk).

**Comment by willpower2727** [comment]
So a hypothetical question then (I've never done this but I have been tempted):

What would happen if I simply labeled strides with bad events as bad but did not delete them. Will this method ultimately change the outcome of the subjects' data?

Say for example, I was processing a stroke control subject who had a trial with some bad events. If I labeled them as bad but did not delete them, would you notice?

I guess I am curious about the reasoning behind splicing strides across a bad event instead of just ignoring it.

**Comment by pabloi** [comment]
The output will be different, no question. The idea behind deleting events
is to offer the possibility to correct errors by the automatic event
detection algorithm, and salvage as much data as possible (e.g. let's say
that the algorithm has a false heel strike detected at the first stride of
a trial for some reason. It would be nice to delete that, so that we keep
the information about what the subject actually did on that stride).

When you label as bad, you are saying 'don't look here', which may or may
not be what you want to do in a specific situation. It is certainly easier
to do, but it may cause some data to be lost (or more precisely, ignored).
It may also affect the counting of strides (let's say that the trial had
exactly 300 strides, but if you have bad events which you do not remove or
miss some events, you may be counting more or less strides for that trial).

I believe that as long as the strides don't happen at the beginning of the
trial (let's say first 10-20 strides), and there aren't too many (let's say
less than 1%) or they are clumped too close together (as to affect the
stride count too much) we shouldn't notice.


On Wed, Oct 7, 2015 at 11:45 AM, willpower2727 <notifications@github.com>
wrote:

> So a hypothetical question then (I've never done this but I have been
> tempted):
>
> What would happen if I simply labeled strides with bad events as bad but
> did not delete them. Will this method ultimately change the outcome of the
> subjects' data?
>
> Say for example, I was processing a stroke control subject who had a trial
> with some bad events. If I labeled them as bad but did not delete them,
> would you notice?
>
> I guess I am curious about the reasoning behind splicing strides across a
> bad event instead of just ignoring it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pabloi/labTools/issues/11#issuecomment-146239617>.
>



-- 
Pablo A. Iturralde
