### ISSUE TITLE
More than 15 experiment conditions

### ISSUE THREAD

**Issue by willpower2727** [pabloi/labTools#13]
Is it easy to alter the c3d2mat gui to allow for more than 15 conditions?

**Comment by pabloi** [comment]
Somewhat easy, I think (I didn't write it). Besides changing the GetIngoGUI itself to have more boxes to input text, you need to change GetInfoGUI to have the additional callbacks, and in lines 278-284 enable the possibility for more conditions (you are not allowed to say that there are more than 15 conditions currently).
The hardest part is that we would also need to modify the save/load mechanisms so that the additional conditions don't get lost when saving and loading. Changes may also be needed in 'errorProofInfo' a function that checks for all data inputed to be coherent.

**Comment by pabloi** [comment]
➤ andertonwill commented:
I created c3d2matbeta function with accompanying GUI to allow for N number of conditions, I've tested on basic data, but not on data with EMG, but I doubt there would be issues.
